name: Prettify HTML File 
description: Prettified an HTML file in-place using BeautifulSoup
inputs:
  filename:
    description: File to Prettify
    required: true
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: |-
        python -m pip install --upgrade pip
        pip install bs4
      shell: bash
    - name: Prettify
      run: python $/prettify.py "${{ inputs.filename }}"
      shell: bash