name: "Andalucia: 📙 BOJA"

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '26 * * * *'

jobs:
  descarga-normativa-covid:
    name: Descargar Normativa COVID-19
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7' 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv sync
      shell: bash
    - name: Descargar resumen pandemia
      uses: ./.github/actions/curl 
      with: 
        url: "https://www.juntadeandalucia.es/servicios/normativa/covid-19.html"
        output-file: documentos/España/Andalucia/normativa/covid-19.html
    - name: Descargar normativa consolidada de medidas preventivas
      uses: ./.github/actions/curl 
      with: 
        url: https://www.juntadeandalucia.es/export/drupaljda/orden_19_06_2020_consolidado.pdf
        output-file: documentos/España/Andalucia/normativa/covid-19-consolidada.pdf
    - name: Limpiar ficheros
      run: pipenv run python ./scripts/andalucia-limpiar-boja.py
      shell: bash
    - name: Commit and push if it changed
      uses: ./.github/actions/commit-changes
      with:
        commit-message: "📙 [Andalucia] BOJA: ${timestamp}"