name: "Comunidad Valenciana: 📙 DOGV"

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '6 * * * *'

jobs:
  descarga-normativa-pandemia:
    name: Descargar resumen COVID-19 DOGV
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv sync
      shell: bash
    - name: Descargar resumen pandemia
      uses: ./.github/actions/curl 
      with: 
        url: "https://www.dogv.gva.es/es/covid-19"
        output-file: documentos/España/Comunitat Valenciana/normativa/covid-19.html
    - name: Limpiar fichero
      run: pipenv run python ./scripts/valencia-limpiar-ficheros.py
    - name: Commit and push if it changed
      uses: ./.github/actions/commit-changes
      with:
        commit-message: "📙 [Comunitat Valenciana] Actualización de DOGV: ${timestamp}"