name: "Castilla-La Mancha: 📙 DOCM"

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '26 * * * *'

jobs:
  descarga-normativa-pandemia:
    name: Descsrga Listado COVID
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Descargar resumen pandemia
      uses: ./.github/actions/curl 
      with: 
        url: "https://docm.castillalamancha.es/portaldocm/listadoCOVID.do"
        output-file: documentos/España/Castilla-La Mancha/normativa/covid-19.html
    - name: Commit and push if it changed
      uses: ./.github/actions/commit-changes
      with:
        commit-message: "📙 [Castilla-La Mancha] Actualización de DOCM: ${timestamp}"