name: "Catalunya: Actualizar Datos de Gencat - Interior"

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '6,26,46 * * * *'

jobs:
  descarga-normativa-pandemia:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Descargar nuevas medidas - español
      run: |
        curl "http://interior.gencat.cat/es/arees_dactuacio/proteccio_civil/consells_autoproteccio_emergencia/malalties-transmissibles-emergents-amb-potencial-alt-risc-/noves-mesures-per-contenir-els-brots-covid-19/index.html" -o "documentos/España/Catalunya/interior/Nuevas medidas para contener los brotes COVID-19.html"
    - name: Descargar nuevas medidas - catalá
      run: |
        curl "http://interior.gencat.cat/ca/arees_dactuacio/proteccio_civil/consells_autoproteccio_emergencia/malalties-transmissibles-emergents-amb-potencial-alt-risc-/noves-mesures-per-contenir-els-brots-covid-19/" -o "documentos/España/Catalunya/interior/Noves mesures per contenir els brots COVID-19.html"
    - name: Commit and push if it changed
      uses: ./.github/actions/commit-changes
      with:
        commit-message: ":notebook: Catalunya: Actualización de Informacion Interior: ${timestamp}"