name: "Catalunya: 游늽 Gencat"

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '6 * * * *'

jobs:
  descarga-normativa-pandemia:
    name: Descargar P치ginas COVID - Interior
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Descargar nuevas medidas - espa침ol
      uses: ./.github/actions/curl 
      with: 
        url: "http://interior.gencat.cat/es/arees_dactuacio/proteccio_civil/consells_autoproteccio_emergencia/malalties-transmissibles-emergents-amb-potencial-alt-risc-/noves-mesures-per-contenir-els-brots-covid-19/index.html" 
        output-file: "documentos/Espa침a/Catalunya/interior/Nuevas medidas para contener los brotes COVID-19.html"
    - name: Descargar nuevas medidas - catal치
      uses: ./.github/actions/curl 
      with: 
        url: "http://interior.gencat.cat/ca/arees_dactuacio/proteccio_civil/consells_autoproteccio_emergencia/malalties-transmissibles-emergents-amb-potencial-alt-risc-/noves-mesures-per-contenir-els-brots-covid-19/" 
        output-file: "documentos/Espa침a/Catalunya/interior/Noves mesures per contenir els brots COVID-19.html"
    - name: Commit and push if it changed
      uses: ./.github/actions/commit-changes
      with:
        commit-message: "游늽 [Catalunya] Actualizaci칩n de Gencat - Interior: ${timestamp}"