name: "España - :blue-book: BOE"
on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '6 * * * *'

jobs:
  descargar-codigos:
    name: Descarga Códigos COVID-19
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv sync
    - name: Leer Índice
      uses: ./.github/actions/curl 
      with: 
        url: "https://www.boe.es/biblioteca_juridica/index.php?lang=es&tipo=C&modo=1" 
        output-file: documentos/nacional/boe/codigos/codigos.html
    - name: Sacar Enlaces a Codigos
      run: pipenv run python ./scripts/listar-codigos-boe.py
    - name: Descargar lista de normas desde Codigos
      run: pipenv run python ./scripts/descargar-codigos-boe.py
    - name: Descargar la normativa consolidada
      run: pipenv run python ./scripts/descargar-normativa-boe.py
    - name: Commit and push if it changed
      uses: ./.github/actions/commit-changes
      with:
        commit-message: ":blue_book: **BOE** Código COVID-19: ${timestamp}"
  
extraer-eu-ccaa:
  name: Extraer Normativa UE, CCAA
  runs-on: ubuntu-latest
  steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv sync
    - name: Extraer indice de normativa UE y autonómica
      run: pipenv run python ./scripts/extraer-normativa-europea-y-autonomica-boe.py
    - name: Commit and push if it changed
      uses: ./.github/actions/commit-changes
      with:
        commit-message: ":blue_book: **BOE** UE/CCAA: ${timestamp}"

descargar-normativa:
  name: Descargar Normativa
  needs: descargar-codigos
  runs-on: ubuntu-latest
  steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv sync
    - name: Descargar la normativa consolidada
      run: pipenv run python ./scripts/descargar-normativa-boe.py
    - name: Commit and push if it changed
      uses: ./.github/actions/commit-changes
      with:
        commit-message: ":blue_book: **BOE** Normativa: ${timestamp}"
  
    