name: "Extremadura: Actualizar Datos del DOE"

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '26 * * * *'

jobs:
  descarga-normativa-pandemia:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Descargar resumen pandemia
      uses: ./.github/actions/curl 
      with: 
        url: "http://doe.gobex.es/covid/covid.pdf"
        output-file: documentos/España/Extremadura/normativa/covid.pdf
    - name: Commit and push if it changed
      uses: ./.github/actions/commit-changes
      with:
        commit-message: ":orange_book: Extremadura: Actualización de DOE: ${timestamp}"